# name = "esl-trpc"                 # Production
name = "esl-trpc-test"            # Test
main = "src/index.ts"
compatibility_date = "2023-07-18"

kv_namespaces = [
  { binding = "KV", id = "0a083bd1f2e846c98605e26ba56f3e97", preview_id = "504101e8d62b435697d8a445d102925d" },
]

[[d1_databases]]
binding = "DB"
# database_name = "esl"                                # Production
# database_id = "5ac1b98b-3ca6-4079-8064-44e00c6d7f92" # Production
database_name = "esl-test"                           # Test
database_id = "6693c304-6758-4411-a7a7-64b3d935ae60" # Test

[triggers]
# crons = ["9,19,29,39,49,59 * * * *"] # Production
crons = ["1 * * 1 *"] # Dev

[dev]
port = 5000
